print('hi world!')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
print('DSLKFJSLDFJ')
